apiVersion: apps/v1
kind: Deployment
metadata:
  name: bike-store-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bike-store-ns
  template:
    metadata:
      labels:
        app: bike-store-ns
    spec:
      containers:
      - name: bike-store-ns
        image: nikolaanicic/city-store
        env:
          - name: CONFIG_PATH
            value: /etc/config/config.yaml
          - name: CITYSTORE_DB_USER
            valueFrom:
              secretKeyRef:
                name: citystore-db-creds
                key: CITYSTORE_DB_USER
          - name: CITYSTORE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: citystore-db-creds
                key: CITYSTORE_DB_PASSWORD
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: city-config
            mountPath: /etc/config/config.yaml
            subPath: config.yaml
            readOnly: true
          - name: citystore-db-password
            mountPath: /run/secrets/citystore-db-password
            subPath: MYSQL_ROOT_PASSWORD_FILE
            readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"

      - name: citystore-db
        image: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD_FILE
            value: /run/secrets/citystore-db-password
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: citystore-db-password
            mountPath: /run/secrets/citystore-db-password
            subPath: MYSQL_ROOT_PASSWORD_FILE
            readOnly: true
          - mountPath: /var/lib/mysql
            name: datans
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "1"
      volumes:
        - name: city-config
          configMap:
            name: city-config
        - name: citystore-db-password
          secret:
            secretName: citystore-db-password
        - name: datans
          persistentVolumeClaim:
            claimName: host-pvc-ns

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bike-store-kg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bike-store-kg
  template:
    metadata:
      labels:
        app: bike-store-kg
    spec:
      containers:
      - name: bike-store-kg
        image: nikolaanicic/city-store
        env:
          - name: CONFIG_PATH
            value: /etc/config/config.yaml
          - name: CITYSTORE_DB_USER
            valueFrom:
              secretKeyRef:
                name: citystore-db-creds
                key: CITYSTORE_DB_USER
          - name: CITYSTORE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: citystore-db-creds
                key: CITYSTORE_DB_PASSWORD
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: city-config
            mountPath: /etc/config/config.yaml
            subPath: config.yaml
            readOnly: true
          - name: citystore-db-password
            mountPath: /run/secrets/citystore-db-password
            subPath: MYSQL_ROOT_PASSWORD_FILE
            readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"

      - name: citystore-db
        image: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD_FILE
            value: /run/secrets/citystore-db-password
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: citystore-db-password
            mountPath: /run/secrets/citystore-db-password
            subPath: MYSQL_ROOT_PASSWORD_FILE
            readOnly: true
          - mountPath: /var/lib/mysql
            name: datans
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "1"
      volumes:
        - name: city-config
          configMap:
            name: city-config
        - name: citystore-db-password
          secret:
            secretName: citystore-db-password
        - name: datans
          persistentVolumeClaim:
            claimName: host-pvc-kg
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bike-store-su
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bike-store-su
  template:
    metadata:
      labels:
        app: bike-store-su
    spec:
      containers:
      - name: bike-store-su
        image: nikolaanicic/city-store
        env:
          - name: CONFIG_PATH
            value: /etc/config/config.yaml
          - name: CITYSTORE_DB_USER
            valueFrom:
              secretKeyRef:
                name: citystore-db-creds
                key: CITYSTORE_DB_USER
          - name: CITYSTORE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: citystore-db-creds
                key: CITYSTORE_DB_PASSWORD
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: city-config
            mountPath: /etc/config/config.yaml
            subPath: config.yaml
            readOnly: true
          - name: citystore-db-password
            mountPath: /run/secrets/citystore-db-password
            subPath: MYSQL_ROOT_PASSWORD_FILE
            readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"

      - name: citystore-db
        image: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD_FILE
            value: /run/secrets/citystore-db-password
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: citystore-db-password
            mountPath: /run/secrets/citystore-db-password
            subPath: MYSQL_ROOT_PASSWORD_FILE
            readOnly: true
          - mountPath: /var/lib/mysql
            name: datans
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "1"
      volumes:
        - name: city-config
          configMap:
            name: city-config
        - name: citystore-db-password
          secret:
            secretName: citystore-db-password
        - name: datans
          persistentVolumeClaim:
            claimName: host-pvc-su
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: centralstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centralstore
  template:
    metadata:
      labels:
        app: centralstore
    spec:
      containers:
      - name: centralstore
        image: nikolaanicic/central_store
        env:
          - name: CONFIG_PATH
            value: /etc/config/config.yaml
          - name: CENTRALSTORE_DB_USER
            valueFrom:
              secretKeyRef:
                name: centralstore-db-creds
                key: CENTRALSTORE_DB_USER
          - name: CENTRALSTORE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: centralstore-db-creds
                key: CENTRALSTORE_DB_PASSWORD
        ports:
          - containerPort: 5000
        volumeMounts:
          - name: central-config
            mountPath: /etc/config/config.yaml
            subPath: config.yaml
            readOnly: true
          - name: centralstore-db-password
            mountPath: /run/secrets/centralstore-db-password
            subPath: MYSQL_ROOT_PASSWORD_FILE
            readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"

      - name: centralstore-db
        image: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD_FILE
            value: /run/secrets/centralstore-db-password
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: centralstore-db-password
            mountPath: /run/secrets/centralstore-db-password
            subPath: MYSQL_ROOT_PASSWORD_FILE
            readOnly: true
          - mountPath: /var/lib/mysql
            name: datans
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "1"
      volumes:
        - name: central-config
          configMap:
            name: central-config
        - name: centralstore-db-password
          secret:
            secretName: centralstore-db-password
        - name: datans
          persistentVolumeClaim:
            claimName: host-pvc-central

---