apiVersion: v1
kind: Service
metadata:
  name: bike-store-ns
spec:
  selector:
    app: bike-store-ns
  ports:
    - protocol: 'TCP'
      port: 8080
      targetPort: 8080
  type: NodePort
---

apiVersion: v1
kind: Service
metadata:
  name: bike-store-kg
spec:
  selector:
    app: bike-store-kg
  ports:
    - protocol: 'TCP'
      port: 8080
      targetPort: 8080
  type: NodePort
---

apiVersion: v1
kind: Service
metadata:
  name: bike-store-su
spec:
  selector:
    app: bike-store-su
  ports:
    - protocol: 'TCP'
      port: 8080
      targetPort: 8080
  type: NodePort
---

apiVersion: v1
kind: Service
metadata:
  name: centralstore
spec:
  selector:
    app: centralstore
  ports:
    - protocol: 'TCP'
      port: 5000
      targetPort: 5000
  type: NodePort
---